targets:
  $default:
    builders:
      # Freezed for immutable data classes
      freezed|freezed:
        generate_for:
          - lib/models/*.dart
        options:
          # Generate copyWith methods
          copy_with: true
          # Generate == operator and hashCode
          equal: true
          # Generate toString method
          to_string: true

      # JSON serialization
      json_serializable:
        generate_for:
          - lib/models/*.dart
        options:
          explicit_to_json: true
          field_rename: snake

      # Isar database code generation
      isar_community_generator|isar_generator:
        generate_for:
          - lib/models/*.dart
        options:
          # Watch for schema changes
          auto_increment_id: true

      # Go router code generation
      go_router_builder:
        generate_for:
          - lib/routing/routes/*.dart
          - lib/routing/app_router.dart
        options:
          # Generate type-safe routes
          route_data_class_prefix: ""
